name: Build and deploy Vite app to Azure Web App - SIMBIOSYS-app

on:
  push:
    branches:
      - azure-teste
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Instalar dependências e buildar
        run: |
          npm install
          npm run build

      - name: Login na Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B8FE014B39C4410B0FB29B744ECD9E2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA8AEF134E57487091B15FA4945A46E0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_027BA4DBF57E49B79D70DAC2700F61FF }}

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SIMBIOSYS-app'
          slot-name: 'Production'
          package: './dist'  # 👈 ESSENCIAL: envia apenas os arquivos do build

          